name: Python application with serial
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install Emulator
      run: |
        curl https://sourceforge.net/projects/com0com/files/com0com/2.2.2.0/com0com-2.2.2.0-x64-fre-signed.zip/download -L -o ./com0com.zip
        tar -xf Name.zip
        com0com-2.2.2.0-x64-fre-signed\setup.exe /S CNC_INSTALL_CNCA0_CNCB0_PORTS=YES /D=C:\"Program Files"\com0com
        copy C:\"Program Files"\com0com\com0com.inf .\com0com.inf
        C:\"Program Files"\com0com\setupc.exe "change CNCA0 PortName=COM1"
        C:\"Program Files"\com0com\setupc.exe "change CNCB0 PortName=COM2"
      shell: cmd
    - name: Install
      run: |
        python -m pip install .[dev]
        python -m pip install wheel
    - name: Test
      run: |
        python -m pytest serial_tests/
    - name: Build
      run: |
        python setup.py bdist_wheel
    - name: Upload a build artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./dist/*.whl
