name: Python application
on:
  workflow_dispatch:
  push:
    tags: ["*"]
    branches: ["*"]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install Emulator
      run: |
        setup.exe /S CNC_INSTALL_CNCA0_CNCB0_PORTS=YES /D=C:\"Program Files (x86)"\com0com
        copy C:\"Program Files (x86)"\com0com\com0com.inf .\com0com.inf
        C:\"Program Files (x86)"\com0com\setupc.exe "install PortName=COM1 PortName=COM2"
      shell: cmd
    - name: Install
      run: |
        python -m pip install .[dev]
        python -m pip install wheel
    - name: Test
      run: |
        python -m pytest tests/
    - name: Build
      run: |
        python setup.py bdist_wheel
    - name: Upload a build artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./dist/*.whl
